package com.portfoliopro.service;
import com.portfoliopro.dto.*; import com.portfoliopro.entity.*; import com.portfoliopro.repository.*; import org.springframework.stereotype.Service; import java.math.*; import java.util.*;
@Service public class PortfolioService {
 private final UserRepository users; private final PortfolioRepository portfolios; private final HoldingRepository holdings; private final TransactionRepository transactions; private final WatchlistRepository watchlist; private final StockRepository stocks;
 public PortfolioService(UserRepository users,PortfolioRepository portfolios,HoldingRepository holdings,TransactionRepository transactions,WatchlistRepository watchlist,StockRepository stocks){this.users=users;this.portfolios=portfolios;this.holdings=holdings;this.transactions=transactions;this.watchlist=watchlist;this.stocks=stocks;}
 public List<HoldingResponse> holdings(Long userId){Portfolio p=portfolio(userId); return holdings.findByPortfolioId(p.getId()).stream().filter(h->h.getQuantity()>0).map(this::holdingDto).toList();}
 public DashboardResponse dashboard(Long userId){User u=user(userId); List<HoldingResponse> hs=holdings(userId); BigDecimal invested=hs.stream().map(HoldingResponse::investedValue).reduce(BigDecimal.ZERO,BigDecimal::add); BigDecimal current=hs.stream().map(HoldingResponse::currentValue).reduce(BigDecimal.ZERO,BigDecimal::add); BigDecimal pnl=current.subtract(invested); List<TransactionResponse> tx=transactions.findByUserIdOrderByCreatedAtDesc(userId).stream().limit(8).map(this::txDto).toList(); List<StockResponse> wl=watchlist.findByUserId(userId).stream().map(w->stockDto(w.getStock())).toList(); return new DashboardResponse(u.getBalance(),invested,current,pnl,hs.size(),hs,tx,wl,riskWarnings(hs)); }
 public List<TransactionResponse> transactions(Long userId){return transactions.findByUserIdOrderByCreatedAtDesc(userId).stream().map(this::txDto).toList();}
 public List<StockResponse> watchlist(Long userId){return watchlist.findByUserId(userId).stream().map(w->stockDto(w.getStock())).toList();}
 public void addWatch(Long userId,Long stockId){User u=user(userId);Stock s=stock(stockId);if(watchlist.findByUserIdAndStockId(u.getId(),s.getId()).isEmpty()){Watchlist w=new Watchlist();w.setUser(u);w.setStock(s);watchlist.save(w);}}
 public void removeWatch(Long userId,Long stockId){watchlist.findByUserIdAndStockId(userId,stockId).ifPresent(watchlist::delete);}
 public User user(Long id){return users.findById(id).orElseThrow(()->new IllegalArgumentException("User not found"));} public User userByEmail(String email){return users.findByEmail(email).orElseThrow(()->new IllegalArgumentException("User not found"));}
 public Portfolio portfolio(Long userId){return portfolios.findByUserId(userId).orElseThrow(()->new IllegalArgumentException("Portfolio not found"));}
 public Stock stock(Long id){return stocks.findById(id).orElseThrow(()->new IllegalArgumentException("Stock not found"));}
 private HoldingResponse holdingDto(Holding h){BigDecimal invested=h.getAverageBuyPrice().multiply(BigDecimal.valueOf(h.getQuantity()));BigDecimal current=h.getStock().getCurrentPrice().multiply(BigDecimal.valueOf(h.getQuantity()));return new HoldingResponse(h.getId(),h.getStock().getSymbol(),h.getStock().getCompanyName(),h.getStock().getSector(),h.getQuantity(),h.getAverageBuyPrice(),h.getStock().getCurrentPrice(),invested,current,current.subtract(invested));}
 private TransactionResponse txDto(Transaction t){return new TransactionResponse(t.getId(),t.getStock().getSymbol(),t.getStock().getCompanyName(),t.getType().name(),t.getQuantity(),t.getPrice(),t.getTotalValue(),t.getCreatedAt());}
 private StockResponse stockDto(Stock s){return new StockResponse(s.getId(),s.getSymbol(),s.getCompanyName(),s.getCurrentPrice(),s.getPreviousPrice(),s.getMarketCap(),s.getPeRatio(),s.getEps(),s.getWeek52High(),s.getWeek52Low(),s.getDayChangePercent(),s.getSector());}
 private List<String> riskWarnings(List<HoldingResponse> hs){List<String> w=new ArrayList<>();BigDecimal total=hs.stream().map(HoldingResponse::currentValue).reduce(BigDecimal.ZERO,BigDecimal::add);if(total.signum()>0){for(HoldingResponse h:hs){if(h.currentValue().multiply(BigDecimal.valueOf(100)).compareTo(total.multiply(BigDecimal.valueOf(40)))>0){w.add("High concentration in "+h.symbol()+" (over 40% of portfolio).");break;}}Map<String,BigDecimal> sector=new HashMap<>();for(HoldingResponse h:hs)sector.merge(h.sector(),h.currentValue(),BigDecimal::add);for(var e:sector.entrySet()){if(e.getValue().multiply(BigDecimal.valueOf(100)).compareTo(total.multiply(BigDecimal.valueOf(50)))>0){w.add("High sector concentration in "+e.getKey()+" (over 50%).");break;}}}BigDecimal pnl=hs.stream().map(HoldingResponse::profitLoss).reduce(BigDecimal.ZERO,BigDecimal::add);if(total.signum()>0 && pnl.multiply(BigDecimal.valueOf(100)).compareTo(total.multiply(BigDecimal.valueOf(-10)))<0)w.add("Portfolio has a loss greater than 10% of current value.");return w;}
}
