package com.portfoliopro.service;
import com.portfoliopro.dto.TradeRequest; import com.portfoliopro.entity.*; import com.portfoliopro.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.*; import java.time.LocalDateTime;
@Service public class TradeService {
 private final UserRepository users; private final StockRepository stocks; private final PortfolioRepository portfolios; private final HoldingRepository holdings; private final TradeRepository trades; private final TransactionRepository transactions;
 public TradeService(UserRepository users,StockRepository stocks,PortfolioRepository portfolios,HoldingRepository holdings,TradeRepository trades,TransactionRepository transactions){this.users=users;this.stocks=stocks;this.portfolios=portfolios;this.holdings=holdings;this.trades=trades;this.transactions=transactions;}
 @Transactional public Trade execute(String email,TradeRequest r){User u=users.findByEmail(email).orElseThrow(()->new IllegalArgumentException("User not found"));Stock s=stocks.findBySymbol(r.symbol().trim().toUpperCase()).orElseThrow(()->new IllegalArgumentException("Stock not found"));TradeType type;try{type=TradeType.valueOf(r.type().trim().toUpperCase());}catch(Exception e){throw new IllegalArgumentException("Trade type must be BUY or SELL");}int qty=r.quantity();if(qty<=0)throw new IllegalArgumentException("Quantity must be greater than zero");BigDecimal total=s.getCurrentPrice().multiply(BigDecimal.valueOf(qty));Portfolio p=portfolios.findByUserId(u.getId()).orElseThrow(()->new IllegalArgumentException("Portfolio not found"));Holding h=holdings.findByPortfolioIdAndStockId(p.getId(),s.getId()).orElse(null);
   if(type==TradeType.BUY){if(u.getBalance().compareTo(total)<0)throw new IllegalArgumentException("Insufficient balance for BUY");u.setBalance(u.getBalance().subtract(total));if(h==null){h=new Holding();h.setPortfolio(p);h.setStock(s);h.setQuantity(qty);h.setAverageBuyPrice(s.getCurrentPrice());}else{BigDecimal oldCost=h.getAverageBuyPrice().multiply(BigDecimal.valueOf(h.getQuantity()));h.setQuantity(h.getQuantity()+qty);h.setAverageBuyPrice(oldCost.add(total).divide(BigDecimal.valueOf(h.getQuantity()),4,RoundingMode.HALF_UP));}}
   else{if(h==null||h.getQuantity()<qty)throw new IllegalArgumentException("Insufficient holdings for SELL");u.setBalance(u.getBalance().add(total));h.setQuantity(h.getQuantity()-qty);}
   if(h!=null){if(h.getQuantity()==0)holdings.delete(h);else holdings.save(h);}users.save(u);
   Trade t=new Trade();t.setUser(u);t.setStock(s);t.setType(type);t.setQuantity(qty);t.setPrice(s.getCurrentPrice());t.setTotalValue(total);t.setExecutedAt(LocalDateTime.now());trades.save(t);
   Transaction tx=new Transaction();tx.setUser(u);tx.setStock(s);tx.setType(type);tx.setQuantity(qty);tx.setPrice(s.getCurrentPrice());tx.setTotalValue(total);tx.setCreatedAt(LocalDateTime.now());transactions.save(tx);return t;
 }
}
